version: '3.4' 

services:

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    hostname: azurite
    restart: always
    ports:
      - 10000:10000
      - 10001:10001
      - 10002:10002
    volumes:
      - /workspaces/data:/data

  api:
    image: woodgrovebank-api:latest
    build:
      context: .
      dockerfile: API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ORLEANS_AZURE_STORAGE_CONNECTION_STRING=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;QueueEndpoint=http://azurite:10001/devstoreaccount1;TableEndpoint=http://azurite:10002/devstoreaccount1;
    hostname: api
    ports:
      - 5000:80
      - 11111:11111
      - 30000:30000
    depends_on:
      - azurite

  admin:
    image: woodgrovebank-admin:latest
    build:
      context: .
      dockerfile: Admin/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ORLEANS_AZURE_STORAGE_CONNECTION_STRING=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;QueueEndpoint=http://azurite:10001/devstoreaccount1;TableEndpoint=http://azurite:10002/devstoreaccount1;
    hostname: admin
    ports:
      - 5001:80
      - 11112:11111
      - 30002:30000

  atm:
    image: woodgrovebank-atm:latest
    build:
      context: .
      dockerfile: ATM/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    hostname: atm
    ports:
      - 5002:80
      - 11113:11111
      - 30003:30000

  dashboard:
    image: woodgrovebank-dashboard:latest
    build:
      context: .
      dockerfile: Dashboard/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ORLEANS_AZURE_STORAGE_CONNECTION_STRING=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;QueueEndpoint=http://azurite:10001/devstoreaccount1;TableEndpoint=http://azurite:10002/devstoreaccount1;
    hostname: api
    ports:
      - 5003:80
      - 11114:11111
      - 30004:30000

  orleans-scaler:
    image: orleans-scaler:latest
    build:
      context: .
      dockerfile: Scaler/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ORLEANS_AZURE_STORAGE_CONNECTION_STRING=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;QueueEndpoint=http://azurite:10001/devstoreaccount1;TableEndpoint=http://azurite:10002/devstoreaccount1;
    hostname: orleans-scaler
    ports:
      - 80:80
      - 11115:11111
      - 30005:30000
      
