apiVersion: apps/v1
kind: Deployment
metadata:
  name: azurite-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: azurerite
      usage: test
  template:
    metadata:
      labels:
        app: azurerite
        usage: test
    spec:
      containers:
      - name: azurite-container
        image: mcr.microsoft.com/azure-storage/azurite
        
        ports:
        - containerPort: 10000
        - containerPort: 10001
        - containerPort: 10002

---
apiVersion: v1
kind: Service
metadata:
  name: azurite-service
spec:
  ports:
  - name: azurite-blobs
    port: 10000
    targetPort: 10000 
  - name: azurite-queues
    port: 10001
    targetPort: 10001
  - name: azurite-tables
    port: 10002
    targetPort: 10002
  selector:
    app: azurerite

---
apiVersion: v1
kind: Secret
metadata:
  name: storage-connection-strings
type: Opaque
data:
  clustering: RGVmYXVsdEVuZHBvaW50c1Byb3RvY29sPWh0dHA7QWNjb3VudE5hbWU9ZGV2c3RvcmVhY2NvdW50MTtBY2NvdW50S2V5PUVieTh2ZE0wMnhOT2NxRmxxVXdKUExsbUV0bENEWEoxT1V6RlQ1MHVTUlo2SUZzdUZxMlVWRXJDejRJNnRxL0sxU1pGUFRPdHIvS0JIQmVrc29HTUd3PT07QmxvYkVuZHBvaW50PWh0dHA6Ly9henVyaXRlLXNlcnZpY2U6MTAwMDAvZGV2c3RvcmVhY2NvdW50MTtRdWV1ZUVuZHBvaW50PWh0dHA6Ly9henVyaXRlLXNlcnZpY2U6MTAwMDEvZGV2c3RvcmVhY2NvdW50MTtUYWJsZUVuZHBvaW50PWh0dHA6Ly9henVyaXRlLXNlcnZpY2U6MTAwMDIvZGV2c3RvcmVhY2NvdW50MTs=