apiVersion: v1
kind: Service
metadata:
  name: orleans-scaler
spec:
  selector:
    app: orleans-scaler
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orleans-scaler
  labels:
    orleans/serviceId: woodgrovebank
spec:
  selector:
    matchLabels:
      app: orleans-scaler
      orleans/serviceId: woodgrovebank
  template:
    metadata:
      labels:
        app: orleans-scaler
        orleans/serviceId: woodgrovebank
        orleans/clusterId: woodgrovebank
    spec:
      containers:
      - name: orleans-scaler
        image: k3d-myregistry.localhost:12345/orleans-scaler:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        - containerPort: 30000
        - containerPort: 11111
        env:
          - name: ORLEANS_SERVICE_ID
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['orleans/serviceId']
          - name: ORLEANS_CLUSTER_ID
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['orleans/clusterId']
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: ORLEANS_AZURE_STORAGE_CONNECTION_STRING
            valueFrom: 
              secretKeyRef: 
                key: clustering
                name: storage-connection-strings
          - name: ASPNETCORE_ENVIRONMENT
            value: 'Development'
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: orleans-scaler-scaledobject
spec:
  pollingInterval: 30
  scaleTargetRef:
    name: woodgrovebank-api
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
    - type: external
      metadata:
        scalerAddress: orleans-scaler:80
        graintype: 'customergrain'
        siloNameFilter: 'woodgrovebank-api'
        upperbound: '60'
        
